### ISSUE TITLE
move to ROOT 6

### ISSUE THREAD

**Issue by dantrim** [gerbaudo/SusyCommon#44]
Moving to the latest AnalysisRelease and SUSYTools means going to ROOT 6 (rcSetup 2.1.27). The code as it stands is unable to output a susyNt after making the change to the newer version of root. The error lies in our use of the D3PDReaderMaker::VarHandle class to read/write out to susyNt, specifically when it calls the "WriteOut" method in SusyNtMaker::InitializeOuputTree (btw "Ouput"-->"Output" :) ). Oddly, the method only causes a crash when attempting to fill the electrons, muons, photons, taus, truthparticles, & truthJets branches but NOT the event, met, and truthMet branches (see SusyNtObject.cxx/.h). 

Within the initialization of the VarHandle "handlers" in SusyNtObject.h these objects are treated the same but in SusyNt.h the Event, Met, and TruthMet classes inherit directly from TObject whereas the others inherit from TObject through an indirect chain (e.g. Lepton->Particle->TLorentzVector->TObject). Could this point to the new ROOT version not producing the correct libraries due to difference in CINT-->CLING? I am in contact with PAT but it would be great if another set of eyes could look into this. As this is preventing the production of susyNt this is very high priority for the migration.

I've attached the error/stack trace.

![screen shot 2015-03-06 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/7841565/6539257/8fb0d214-c424-11e4-9206-d980b8332251.png)

**Comment by dantrim** [comment]
I found the issue(s). Had to make two fixes to the code. 

(1) I had only removed the instances of "#ifdef/ifndef __CINT__" ... I have now replaced with "ifdef/ifndef __CLING__"
(2) In SusyCommon/Root/LinkDef.h on the xaod branch the includes for XaodAnalysis and SusyNtMaker, as well as anything with "namespace susy", are commented out. I have uncommented this. Not sure what the "susy" namespace is for -- to avoid conflict with older SusyCommon?

Welp, one step closer to Run-II !

**Comment by gerbaudo** [comment]
Nice!! Thanks for fixing this!
Are these changes on a branch I can see?
Regarding the namespace `susy` and `Susy`: that's my bad.
The original one was `Susy`, then at some point I introduced `susy`
because lowercase names is a more common convention
for namespaces, see e.g. [google-styleguide](http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Namespace_Names). I promised in #12 to change
to lowercase `susy` everywhere, but I never got around to doing it.
Sorry...opening #45 so that I won't forget again.
